//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerinfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string ismarr { get; set; }
        public string cardNo { get; set; }
        public string address { get; set; }
        public string workunit { get; set; }
        public string workaddress { get; set; }
        public string job { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string detail { get; set; }
        public string user { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> isdel { get; set; }
        public string delInfo { get; set; }
    }
}
